### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by KoXz666** [fracpete/kodi-nfo-generator-addon#1]
Why this kind of tools never working for me? Is there some kodi nfo generator for windows?

**Comment by fracpete** [comment]
You have to provide a few more details. What Python version? What error messages? Can you run the kodi-nfo-generator tool (not the addon!) successfully from the commandline? If yes, what is the commandline? If not, what are the error messages?

**Comment by KoXz666** [comment]
sorry its my fault i quess.. On github i can find awesome tools, but there isnt instalation instructions, or exe file almost everytime.. I dont have error message because i cant find executable file :( thats it.. but dont worry, im sure i can find a way to make multiple nfo files :) i hope

**Comment by fracpete** [comment]
[kodi-nfo-generator](https://github.com/fracpete/kodi-nfo-generator) and this [kodi](https://kodi.tv/) addon (which uses kodi-nfo-generator under the hood) are both written in Python, so you need to have Python installed on your system:
https://www.python.org/downloads/windows/

Not sure whether `pip` (a popular package manager for installing Python libraries) now comes with each Python installation, so you might have to install it manually:
https://pip.pypa.io/en/stable/installation/

Once you have pip, you can install [kodi-nfo-generator](https://github.com/fracpete/kodi-nfo-generator) with something like this:
```command
pip install kodi-nfo-generator
```

Then you should be able to generate `.nfo` files from `.imdb` files using the `kodi-nfo-gen` script. More info on the [kodi-nfo-generator](https://github.com/fracpete/kodi-nfo-generator) project page.

**Comment by fracpete** [comment]
closed due to inactivity
